services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    env_file:
      - .env.dev
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"

  inventory-daemon:
    image: inventory-daemon:dev
    depends_on:
      - redis
    privileged: true
    stdin_open: true
    tty: true
    env_file:
      - .env.dev
    environment:
      INV_REDIS_HOST: redis
    restart: unless-stopped
    volumes:
      - /dev:/dev
      - /sys:/sys:ro
      - /run/udev:/run/udev:ro
      - /mnt:/mnt:rshared

  inventory-service:
    image: inventory-service:dev
    depends_on:
      - redis
    env_file:
      - .env.dev
    ports:
      - "${INV_SERVICE_APP_PORT:-8000}:${INV_SERVICE_APP_PORT:-8000}"
    environment:
      INV_SERVICE_REDIS_HOST: redis
    restart: unless-stopped